"""initial_schema

Revision ID: 06ee783311fa
Revises: 
Create Date: 2026-06-01 15:00:00.775100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06ee783311fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for gen_random_uuid() — see docs/db-schema.md.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'error')", name=op.f('ck_integrations_status')),
    sa.CheckConstraint("type IN ('manual', 'jira', 'azure_devops')", name=op.f('ck_integrations_type')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_integrations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index('idx_integrations_type', 'integrations', ['type', 'workspace_id'], unique=False)
    op.create_index('idx_integrations_workspace', 'integrations', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_projects_integration_id_integrations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('integration_id', 'external_id', name='uq_projects_integration_external_id')
    )
    op.create_index('idx_projects_integration', 'projects', ['integration_id'], unique=False)
    op.create_index('idx_projects_workspace', 'projects', ['workspace_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), server_default=sa.text("'Open'"), nullable=False),
    sa.Column('priority', sa.String(length=50), server_default=sa.text("'Medium'"), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=100), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('area_path', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('reporter', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_system IN ('manual', 'jira', 'azure_devops')", name=op.f('ck_tickets_source_system')),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_tickets_integration_id_integrations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tickets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tickets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index('idx_tickets_fts', 'tickets', [sa.literal_column("to_tsvector('english', title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('idx_tickets_integration', 'tickets', ['integration_id'], unique=False)
    op.create_index('idx_tickets_labels', 'tickets', ['labels'], unique=False, postgresql_using='gin')
    op.create_index('idx_tickets_project', 'tickets', ['project_id'], unique=False)
    op.create_index('idx_tickets_status', 'tickets', ['status', 'priority'], unique=False)
    op.create_index('idx_tickets_tree', 'tickets', ['workspace_id', 'client_name', 'environment'], unique=False)
    op.create_index('idx_tickets_workspace', 'tickets', ['workspace_id'], unique=False)
    op.create_index('uq_tickets_integration_external_id', 'tickets', ['integration_id', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(length=50), server_default=sa.text("'user'"), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('result_markdown', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('similar_tickets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed', 'error')", name=op.f('ck_analysis_runs_status')),
    sa.CheckConstraint("triggered_by IN ('user', 'auto', 'quick_action')", name=op.f('ck_analysis_runs_triggered_by')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_analysis_runs_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index('idx_analysis_pending', 'analysis_runs', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('idx_analysis_result', 'analysis_runs', ['result_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_analysis_ticket_latest', 'analysis_runs', ['ticket_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('ticket_artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), server_default=sa.text("'other'"), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('log', 'screenshot', 'stacktrace', 'config', 'other')", name=op.f('ck_ticket_artifacts_type')),
    sa.CheckConstraint('content IS NOT NULL OR storage_url IS NOT NULL', name=op.f('ck_ticket_artifacts_content_or_url')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_artifacts_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_artifacts'))
    )
    op.create_index('idx_artifacts_ticket', 'ticket_artifacts', ['ticket_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('external', 'internal')", name=op.f('ck_ticket_comments_source')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments'))
    )
    op.create_index('idx_comments_ticket', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comments_ticket', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index('idx_artifacts_ticket', table_name='ticket_artifacts')
    op.drop_table('ticket_artifacts')
    op.drop_index('idx_analysis_ticket_latest', table_name='analysis_runs')
    op.drop_index('idx_analysis_result', table_name='analysis_runs', postgresql_using='gin')
    op.drop_index('idx_analysis_pending', table_name='analysis_runs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('analysis_runs')
    op.drop_index('uq_tickets_integration_external_id', table_name='tickets', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('idx_tickets_workspace', table_name='tickets')
    op.drop_index('idx_tickets_tree', table_name='tickets')
    op.drop_index('idx_tickets_status', table_name='tickets')
    op.drop_index('idx_tickets_project', table_name='tickets')
    op.drop_index('idx_tickets_labels', table_name='tickets', postgresql_using='gin')
    op.drop_index('idx_tickets_integration', table_name='tickets')
    op.drop_index('idx_tickets_fts', table_name='tickets', postgresql_using='gin')
    op.drop_table('tickets')
    op.drop_index('idx_projects_workspace', table_name='projects')
    op.drop_index('idx_projects_integration', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_integrations_workspace', table_name='integrations')
    op.drop_index('idx_integrations_type', table_name='integrations')
    op.drop_table('integrations')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
